package model.type;

public enum BadgeType {
    // Performance Badges
    QUICK_REACTOR_1,
    QUICK_REACTOR_2,
    QUICK_REACTOR_3,
    PERFECT_ACCURACY,

    // Milestone Badges
    ARTIST_QUIZ_MILESTONE_1,
    ARTIST_QUIZ_MILESTONE_3,
    ARTIST_QUIZ_MILESTONE_5,
    ARTIST_QUIZ_MILESTONE_10,
    ARTIST_QUIZ_MILESTONE_25,
    ARTIST_QUIZ_MILESTONE_50,
    PLAYLIST_QUIZ_MILESTONE_1,
    PLAYLIST_QUIZ_MILESTONE_3,
    PLAYLIST_QUIZ_MILESTONE_5,
    PLAYLIST_QUIZ_MILESTONE_10,
    PLAYLIST_QUIZ_MILESTONE_25,
    PLAYLIST_QUIZ_MILESTONE_50,

    // Knowledge Badges
    PLAYLIST_KNOWLEDGE,
    ARTIST_KNOWLEDGE_1,
    ARTIST_KNOWLEDGE_2,
    ARTIST_KNOWLEDGE_3,
    ARTIST_KNOWLEDGE_4,
    STUDIO_ALBUM_KNOWLEDGE,
    OTHER_ALBUM_KNOWLEDGE,
}
